name: "Download BPMN models"
description: 'GitHub Action for automated download of BPMN models from Camunda web modeler api'
author: "Kristoffer Högberg"

inputs:
  tag:
    description: 'Name of the tag model tag to download'
    required: true
  destination:
    description: 'Location of the destination folder for the BPMN models'
    required: true
  token:
    description: 'Camunda modeler api access token'
    required: true

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: 'activity'
  color: 'green'
